### ISSUE TITLE
Interface Cross-Platform Compatibility Issue

### ISSUE THREAD

**Issue by k4yt3x** [K4YT3X/SCUTUM#2]
The program is unable to react to the right interface on Arch Linux and other Linux distributions that has a different interface name other than the hard coded 'wlan0' which was originally for testing purposes only.

Same principle, all other interfaces are unavailable.

**Comment by k4yt3x** [comment]
Jul. 1, 2017: This issue is being fixed in the currently newest version: 2.3 alpha.
Tests are needed to ensure that the problem is being solved.

**Comment by ghost** [comment]
Seems to work fine here!

**Comment by k4yt3x** [comment]
@bryce-lynch try running this
~~~~
$ sudo arptables -L
~~~~

if you see something like this after connecting to a network
~~~~
Chain INPUT (policy DROP)
-j ACCEPT --src-mac 54:64:d6:ec:ad:f8

Chain OUTPUT (policy ACCEPT)

Chain FORWARD (policy ACCEPT)
~~~~
then the program is working correctly

**Comment by ghost** [comment]
It looks like Arch uses arptables-compat instead of arptables. Perhaps you should add a check in scutum to determine which one of the two versions exist.

**Comment by k4yt3x** [comment]
Looks like I still need an Arch to fully test things out. I will try installing one and do a full test on Arch.

**Comment by ghost** [comment]
Just grab an ISO from antergos.com and you have a live Arch on usb, no need to install anything.

**Comment by k4yt3x** [comment]
@bryce-lynch Thanks for the suggestion. What I was facing was the problem enabling virtualization on my AMD motherboard. I just got that sorted out yesterday. I just got my hands on arptables-compat.

Actually, an issue that I'm testing out right now is that the arptables-compat does not show me the MAC address which I ordered it to block. It looks something like this.

![not_working](https://user-images.githubusercontent.com/21986859/27811160-f7dd934a-6030-11e7-8d3f-cb16ffbf9dae.png)

I need to test if it actually blocked the arp from other addresses. I just need a few more VMs to scan the network to make the results certain.

**Comment by k4yt3x** [comment]
@bryce-lynch After a whole day of testing on Arch Linux which I spent half a day to install gnome on, I still can't get arptables-compat working. After typing in the command, the source mac just doesn't show up. Please leave a comment if you know how to solve this problem. However, installing arptables works just fine and this requires only one command:
~~~~
$ sudo pacman -S arptables
~~~~
I can pack this command into SCUTUM so it installs arptables automatically and it should solve all the problems. 

**What do you think?**

**Update 00:24:20 UTC, Thursday, July 6, 2017:**
I have uploaded a newer version. 2.4.1
If you just reinstall the newer version and follow the instructions, it should work perfectly fine.

**Comment by ghost** [comment]
I'm glad to report it works now. arptables -L shows an input chain rule for my router's mac address. Thanks for taking the time to test it and adding compatibility for Arch.

I think you should also detect if avalon is installed (I installed it with sudo pip install avalon_framework) or specify the requirement in the README.

**Comment by k4yt3x** [comment]
Yeah sure. That is part of the plan. I thought about that a long time ago. I just need to figure out which solution is better:

1. Install pip with get-pip.py and install the framework with pip
2. Download the framework .py file diretly from github

I will test things out shortly

update: @bryce-lynch 
I have pushed the newest version which allows installing avalon_framework automatically using 3 different methods. That should do the job.

You can actually try it out and report issues if any. The chatroom address is on the first line of README. You're welcome to be the first one to join :D

**Thank you a lot @bryce-lynch  for all your suggestions so far. They helped the growth of this program and made it a lot better than before. --K4YT3X :D**
