### ISSUE TITLE
Problems with installation

### ISSUE THREAD

**Issue by NetworkJack2** [K4YT3X/SCUTUM#5]
1. First, I take issue with the automated pulling of python packages, especially on linux this can break the file system, leaving packages untracked by the system package manager. Dep checks should fail gracefully
2. You should not be using the main script to install itself
3. You should not be using git from the main script to install itself, doubleplusbad,
4. There is no systemd unit file.
5. the QT gui needs a make file

Instead written instructions should be given and stateful fail messages. you also need an INSTALL file with a clear list of dependencies and instructions.

This would be really nice for the people who actually write packages for distros.

**Comment by k4yt3x** [comment]
1. All python deps are being installed by pip. All packages are installed by package managers. Currently, the dep check will only exit if none of apt or yum or pacman is available. Otherwise it will install packages with package managers after that the user have agreed.

1. I know. This is stupid. I will fix it later.
1. Just like 3
1. I will look into that. This program used to be a 20-line light-weight script. The transition to an actual system service takes some research. It is appreciated if you can tell me more about systemd unit files. I am new with sys services.
1. The QT folder was directly from QT Creator. IDK what happened to the make file, but I will look into that.

I am planning to make .deb files, and yes I will go ahead and record all deps in a INSTALL file.
The code on my computer is still changing rapidly. I will do all the nice little things by the time the stable version comes out.

Thanks for your feedback @GIJack  **:D**

**Comment by k4yt3x** [comment]
@GIJack I've done some small tweaks. The installation should be a bit better by now

**Comment by NetworkJack2** [comment]
>I am planning to make .deb files

Excellent. I will be writing the Arch Linux Package. I already have avalon in AUR:

https://aur.archlinux.org/packages/python-avalon_framework/

>It is appreciated if you can tell me more about systemd unit files. I am new with sys services.

Documentation here:

https://www.freedesktop.org/software/systemd/man/systemd.unit.html\

They are very simply. I tell you what, you get the rest of it done, and I'll write the systemd unit for you based on your init script.

**Comment by k4yt3x** [comment]
Thanks a lot for packing for Arch! I am still trying to figure some parts out along with some unit tests.

I will soon create a requirements list so it will be easier for you to write the package.

Thanks again for helping :D

**Comment by k4yt3x** [comment]
@GIJack  I think I'm done with most of it. The service installation on my server has failed.
Here are some details:
> scutum.service is not a native service, redirecting to systemd-sysv-install.
> Executing: /lib/systemd/systemd-sysv-install enable scutum
> insserv: Script scutum is broken: incomplete LSB comment.
> insserv: missing \`Required-Start:\' entry: please add even if empty.
> insserv: missing \`Required-Stop:\'  entry: please add even if empty.

I will look into that. It will be much appreciated if you can tell me what's going on there. A real person is better than Google. Also, I though it might be related to the systemd unit thing?

Other than that, [DEPENDENCIES.md](https://github.com/K4YT3X/SCUTUM/blob/master/README.md) has been created. You can find all the deps in there. It should be pretty straight-forward.

Thank you for your help.

Best,
K4YT3X

**Comment by NetworkJack2** [comment]
ahh, you basicly put the .service file in /lib/systemd/system and then type

systemctl daemon-reload

it should now show up with systemctl status scutum.

Again, thank you for taking the time for getting back to me. I'm at work right now, so I'll take a close look when I get home.

As promised I will present you with a working systemd .service unit, that you can use as an example for future systemd endeavours.

edit: almost forgot. There isn't a stable release in the releases tab since 2.4.2. I am working with stable releases, but I might add a git version

I also hang out on #archlinux-offtopic on freenode as GI_Jack, so if you have questions of me you can find me there.

edit:

**Comment by k4yt3x** [comment]
@GIJack Thanks. I already have that issue resolved. I needed to add a "Required-Start:" and a "Required-Stop" section. In the init.d script.

With the .service file, I just used update-rc.d to register the service script and it automatically generates a .service file. Idk if I'm missing anything, but this version is already fully working -- so far.

I have my own XMPP network, so I hardly go on other IRC forums. However if I do go to freenode someday, I'd be sure to say hi.

Thanks,
K4YT3X

**Comment by k4yt3x** [comment]
@GIJack I have already created a new pre-release with a deb file. It should be working by now.

The way the deb file was disigned was that it will but all scutum files in /usr/share/scutum and run a post installation script after copying anything. The script calls the command "scutum --install". Then during the installation wizard, SCUTUM is expected to created symbolic links and services files by itself. When removing, "scutum --uninstall" should be called to finish the uninstallation. However, that part is still incomplete in the current version of deb package.

Append:
![aptgrep](https://user-images.githubusercontent.com/21986859/31154273-fd075d2a-a873-11e7-8931-4198dd54e9dc.png)
![succeeded](https://user-images.githubusercontent.com/21986859/31154276-01a8a0be-a874-11e7-9542-f3d58cc81652.png)

**Comment by k4yt3x** [comment]
SCUTUM has passed all tests successfully so far.
If you experience any issue, feel free to open a new issue.

Thank you for your help.
K.
